using System.Collections.Generic;
using ENMT_V2.Core.Model;
using ENMT_V2.Repository.Interface;
using LinqToExcel;
using System.Linq;
using System.IO;
using System.Windows.Forms;

namespace ENMT_V2.Repository
{
    public class WaterfallRepository : IWaterfallRepository
    {
        public string[] GetFilesFromPath()
        {
            string[] filePaths = Directory.GetFiles(Application.StartupPath + "\\Waterfall\\");
            return filePaths;
        }
 
        public IEnumerable<Waterfall_Imp_Data> GetListWaterfall_Imp_Data(string filename)
        {
            var excel = new ExcelQueryFactory();
            excel.FileName = filename;

            var x = excel.GetWorksheetNames();

            var query = (from s in excel.WorksheetRange<Waterfall_Imp_Data>("A2", "XFD1048576", 0) select s).ToList();        

            return query;

            //List<Waterfall_Imp_Data> lstWaterfall_Imp_Data = new List<Waterfall_Imp_Data>();
            //foreach (Waterfall_Imp_Data item in query)
            //{
            //    lstWaterfall_Imp_Data.Add(new Waterfall_Imp_Data
            //    {
            //        ACTUAL_ISSUE_DATE = item.ACTUAL_ISSUE_DATE,
            //        ADDRESS = item.ADDRESS,
            //        AFTRCC_Status = item.AFTRCC_Status,
            //        iComply_Bucket = item.iComply_Bucket,
            //        AFTRCC_Submit = item.AFTRCC_Submit,
            //        BDM_Completed_Date = item.BDM_Completed_Date,
            //        BDM_Status = item.BDM_Status,
            //        BUDGET_YEAR = item.BUDGET_YEAR,
            //        CAPITAL_PROGRAM = item.CAPITAL_PROGRAM,
            //        Carrier_Count = item.Carrier_Count,
            //        CFAS_PROJECT_NUMBER = item.CFAS_PROJECT_NUMBER,
            //        CI003_ACTUAL = item.CI003_ACTUAL,
            //        CI003_FORECAST = item.CI003_FORECAST,
            //        CI004_ACTUAL = item.CI004_ACTUAL,
            //        CI004_FORECAST = item.CI004_FORECAST,
            //        CI020_ACTUAL = item.CI020_ACTUAL,
            //        CI020_FORECAST = item.CI020_FORECAST,
            //        CI025_ACTUAL = item.CI025_ACTUAL,
            //        CI025_FORECAST = item.CI025_FORECAST,
            //        CI030_ACTUAL = item.CI030_ACTUAL,
            //        CI030_FORECAST = item.CI030_FORECAST,
            //        CI031_ACTUAL = item.CI031_ACTUAL,
            //        CI031_FORECAST = item.CI031_FORECAST,
            //        CI032_ACTUAL = item.CI032_ACTUAL,
            //        CI032_FORECAST = item.CI032_FORECAST,
            //        CI034_ACTUAL = item.CI034_ACTUAL,
            //        CI034_FORECAST = item.CI034_FORECAST,
            //        CI035_CI010_ACTUAL = item.CI035_CI010_ACTUAL,
            //        CI035_CI010_FORECAST = item.CI035_CI010_FORECAST,
            //        CI046_ACTUAL = item.CI046_ACTUAL,
            //        CI046_FORECAST = item.CI046_FORECAST,
            //        CI048_ACTUAL = item.CI048_ACTUAL,
            //        CI048_FORECAST = item.CI048_FORECAST,
            //        CI050_ACTUAL = item.CI050_ACTUAL,
            //        CI050_FORECAST = item.CI050_FORECAST,
            //        CI060_ACTUAL = item.CI060_ACTUAL,
            //        CI060_FORECAST = item.CI060_FORECAST,
            //        CI110_ACTUAL = item.CI110_ACTUAL,
            //        CI110_FORECAST = item.CI110_FORECAST,
            //        CI118_ACTUAL = item.CI118_ACTUAL,
            //        CI118_FORECAST = item.CI118_FORECAST,
            //        CI119_ACTUAL = item.CI119_ACTUAL,
            //        CI119_FORECAST = item.CI119_FORECAST,
            //        CI139_ACTUAL = item.CI139_ACTUAL,
            //        CI139_FORECAST = item.CI139_FORECAST,
            //        CI140_ACTUAL = item.CI140_ACTUAL,
            //        CI140_FORECAST = item.CI140_FORECAST,
            //        CI149_ACTUAL = item.CI149_ACTUAL,
            //        CI149_FORECAST = item.CI149_FORECAST,
            //        CI166_ACTUAL = item.CI166_ACTUAL,
            //        CI166_FORECAST = item.CI166_FORECAST,
            //        CI216_ACTUAL = item.CI216_ACTUAL,
            //        CI216_FORECAST = item.CI216_FORECAST,
            //        CI217_ACTUAL = item.CI217_ACTUAL,
            //        CI217_FORECAST = item.CI217_FORECAST,
            //        CIVIL_VENDOR = item.CIVIL_VENDOR,
            //        CL001_ACTUAL = item.CL001_ACTUAL,
            //        CL001_FORECAST = item.CL001_FORECAST,
            //        CL100_ACTUAL = item.CL100_ACTUAL,
            //        CL100_FORECAST = item.CL100_FORECAST,
            //        CL101_ACTUAL = item.CL101_ACTUAL,
            //        CL101_FORECAST = item.CL101_FORECAST,
            //        COMMITTED_POR_ONAIRDATE = item.COMMITTED_POR_ONAIRDATE,
            //        CONSTRUCTION_TYPE = item.CONSTRUCTION_TYPE,
            //        CONVERGED_AC_ed = item.CONVERGED_AC_ed,
            //        CONVERGED_Fcst = item.CONVERGED_Fcst,
            //        COUNTY = item.COUNTY,
            //        Current_Cycle_Time = item.Current_Cycle_Time,
            //        Current_Cycle_Time_Category = item.Current_Cycle_Time_Category,
            //        CURRENT_NEED_BY_DATE = item.CURRENT_NEED_BY_DATE,
            //        CUSTOM_PROGRAM = item.CUSTOM_PROGRAM,
            //        CX_AREA_MANAGER = item.CX_AREA_MANAGER,
            //        C_E_ON_AIR_DATE = item.C_E_ON_AIR_DATE,
            //        DIST_ZONE = item.DIST_ZONE,
            //        EDP_Publish_Date = item.EDP_Publish_Date,
            //        EDP_STATUS = item.EDP_STATUS,
            //        EPL_ProjectBucket01 = item.EPL_ProjectBucket01,
            //        EQUIPMENT_VENDOR = item.EQUIPMENT_VENDOR,
            //        EXECUTED_ON = item.EXECUTED_ON,
            //        FA_LOCATION_CODE = item.FA_LOCATION_CODE,
            //        FA_LOCATION_TYPE = item.FA_LOCATION_TYPE,
            //        Filter_Info = item.Filter_Info,
            //        FIPS_CODE = item.FIPS_CODE,
            //        Funding_Level = item.Funding_Level,
            //        Funding_Level_Handle = item.Funding_Level_Handle,
            //        GATING_BUCKET = item.GATING_BUCKET,
            //        Gating_Bucket_Reason = item.Gating_Bucket_Reason,
            //        High_Trust = item.High_Trust,
            //        INTEGRATION_VENDOR = item.INTEGRATION_VENDOR,
            //        IPLAN_JOB_STATUS = item.IPLAN_JOB_STATUS,
            //        JI009_ACTUAL = item.JI009_ACTUAL,
            //        JI009_FORECAST = item.JI009_FORECAST,
            //        JOB_SCOPE = item.JOB_SCOPE,
            //        JOB_TYPE_SUBTYPE = item.JOB_TYPE_SUBTYPE,
            //        JOB_VENDOR = item.JOB_VENDOR,
            //        LATITUDE = item.LATITUDE,
            //        LCL_Category = item.LCL_Category,
            //        LONGITUDE = item.LONGITUDE,
            //        Max_CED_Bucket = item.Max_CED_Bucket,
            //        Max_CED_for_Project = item.Max_CED_for_Project,
            //        MCEP = item.MCEP,
            //        MODCDParity_Flag = item.MODCDParity_Flag,
            //        MOD_Code = item.MOD_Code,
            //        NATIONAL_PROGRAM = item.NATIONAL_PROGRAM,
            //        ONAIR_ACTUAL = item.ONAIR_ACTUAL,
            //        ONAIR_FORECAST = item.ONAIR_FORECAST,
            //        ONAIR_PLAN = item.ONAIR_PLAN,
            //        ONAIR_TASK = item.ONAIR_TASK,
            //        OPTIMIZATION_VENDOR = item.OPTIMIZATION_VENDOR,
            //        ORACLE_PTN = item.ORACLE_PTN,
            //        ORIGINAL_NEED_BY_DATE = item.ORIGINAL_NEED_BY_DATE,
            //        PACE_NAME = item.PACE_NAME,
            //        PACE_NUMBER = item.PACE_NUMBER,
            //        PLAN_FC_On_Air = item.PLAN_FC_On_Air,
            //        PLAN_YEAR = item.PLAN_YEAR,
            //        PM2_PERSON = item.PM2_PERSON,
            //        PM3_PERSON = item.PM3_PERSON,
            //        POE_Name = item.POE_Name,
            //        POE_Status = item.POE_Status,
            //        POR_Name = item.POR_Name,
            //        POR_ONAIR_PLAN = item.POR_ONAIR_PLAN,
            //        POR_Status = item.POR_Status,
            //        PRIMARY_JOB_NUMBER = item.PRIMARY_JOB_NUMBER,  
            //        PRODUCT_GROUP = item.PRODUCT_GROUP,
            //        PRODUCT_SUBGROUP = item.PRODUCT_SUBGROUP,
            //        PROJECT_MANAGER = item.PROJECT_MANAGER,
            //        PSAP_Bucket = item.PSAP_Bucket,
            //        PSAP_Comments = item.PSAP_Comments,
            //        RAN_FA_Rank = item.RAN_FA_Rank,
            //        RBS_ID = item.RBS_ID,
            //        RE001_ACTUAL = item.RE001_ACTUAL,
            //        RE001_FORECAST = item.RE001_FORECAST,
            //        RE005_ACTUAL = item.RE005_ACTUAL,
            //        RE005_FORECAST = item.RE005_FORECAST,
            //        RE007_ACTUAL = item.RE007_ACTUAL,
            //        RE007_FORECAST = item.RE007_FORECAST,
            //        RE015_ACTUAL = item.RE015_ACTUAL,
            //        RE015_FORECAST = item.RE015_FORECAST,
            //        RE020_ACTUAL = item.RE020_ACTUAL,
            //        RE020_FORECAST = item.RE020_FORECAST,
            //        RE030_ACTUAL = item.RE030_ACTUAL,
            //        RE030_FORECAST = item.RE030_FORECAST,
            //        RE031_ACTUAL = item.RE031_ACTUAL,
            //        RE031_FORECAST = item.RE031_FORECAST,
            //        RE032_ACTUAL = item.RE032_ACTUAL,
            //        RE032_FORECAST = item.RE032_FORECAST,
            //        SAQ_Area_Manager = item.SAQ_Area_Manager,
            //        RE056_ACTUAL = item.RE056_ACTUAL,
            //        RE056_FORECAST = item.RE056_FORECAST,
            //        RE057_ACTUAL = item.RE057_ACTUAL,
            //        RE057_FORECAST = item.RE057_FORECAST,
            //        RE060_ACTUAL = item.RE060_ACTUAL,
            //        RE060_FORECAST = item.RE060_FORECAST,
            //        RE066_ACTUAL = item.RE066_ACTUAL,
            //        RE066_FORECAST = item.RE066_FORECAST,
            //        RE097_ACTUAL = item.RE097_ACTUAL,
            //        RE097_FORECAST = item.RE097_FORECAST,
            //        RFDS_ID= item.RFDS_ID,
            //        RFDS_Issue= item.RFDS_Issue,
            //        RFDS_State_Status = item.RFDS_State_Status,
            //        RFDS_Workflow_Owner= item.RFDS_Workflow_Owner,
            //        RFDS_Workflow_Updated_Date = item.RFDS_Workflow_Updated_Date,
            //        SITE_ACQUISITION_VENDOR = item.SITE_ACQUISITION_VENDOR,
            //        SITE_ID = item.SITE_ID,
            //        Site_Submission_Status = item.Site_Submission_Status,
            //        SOURCE_JOB_NUMBER = item.SOURCE_JOB_NUMBER,
            //        SPECTRUM = item.SPECTRUM,
            //        Spectrum_Bucket = item.Spectrum_Bucket,
            //        SS007_ACTUAL = item.SS007_ACTUAL,
            //        SS007_FORECAST = item.SS007_FORECAST,
            //        SS014_ACTUAL = item.SS014_ACTUAL,
            //        SS014_FORECAST = item.SS014_FORECAST,
            //        SS020_ACTUAL = item.SS020_ACTUAL,
            //        SS020_FORECAST = item.SS020_FORECAST,
            //        SS071_ACTUAL = item.SS071_ACTUAL,
            //        SS071_FORECAST = item.SS071_FORECAST,
            //        SS076_ACTUAL = item.SS076_ACTUAL,
            //        SS076_FORECAST = item.SS076_FORECAST,
            //        SS099_FORECAST = item.SS099_FORECAST,
            //        SS100_ACTUAL= item.SS100_ACTUAL,
            //        SS100_FORECAST = item.SS100_FORECAST,
            //        SS101_ACTUAL= item.SS101_ACTUAL,
            //        SS101_FORECAST =item.SS101_FORECAST,
            //        SS102_ACTUAL = item.SS102_ACTUAL,
            //        SS102_FORECAST = item.SS102_FORECAST,
            //        SSO99_ACTUAL = item.SSO99_ACTUAL,
            //        STATUS = item.STATUS,
            //        STRATEGIC_DRIVER = item.STRATEGIC_DRIVER,
            //        STRUCTURE_TYPE = item.STRUCTURE_TYPE,
            //        TRANSPORT_FORECAST = item.TRANSPORT_FORECAST,
            //        Submission_Status_Validation_Ranking = item.Submission_Status_Validation_Ranking,
            //        Temp = item.Temp,
            //        TEMPLATE_NAME = item.TEMPLATE_NAME,
            //        THIRD_PARTY_OWNERS = item.THIRD_PARTY_OWNERS,
            //        TRANSPORT_ACTUAL = item.TRANSPORT_ACTUAL,
            //        USID = item.USID,
            //        WORK_GROUP = item.WORK_GROUP                 
            //    });
            //}
            //return lstWaterfall_Imp_Data;
        }

        public IEnumerable<Waterfall_NSB_Data> GetListWaterfall_NSB_Data(string filename)
        {
            var excel = new ExcelQueryFactory();
            excel.FileName = filename;

            var x = excel.GetWorksheetNames();

            var query = (from s in excel.WorksheetRange<Waterfall_NSB_Data>("A2", "XFD1048576", 4) select s).ToList();

            return query;
            //List<Waterfall_NSB_Data> lstWaterfall_NSB_Data = new List<Waterfall_NSB_Data>();
            //foreach (Waterfall_NSB_Data item in query)
            //{
            //    lstWaterfall_NSB_Data.Add(new Waterfall_NSB_Data
            //    {
            //        WORK_GROUP = item.WORK_GROUP,
            //        USID = item.USID,
            //        TEMPLATE_NAME = item.TEMPLATE_NAME,
            //        Temp = item.Temp,
            //        Submission_Status_Validation_Ranking = item.Submission_Status_Validation_Ranking,
            //        ACTUAL_ISSUE_DATE = item.ACTUAL_ISSUE_DATE,
            //        ADDRESS = item.ADDRESS,
            //        AFTRCC_Status = item.AFTRCC_Status,
            //        AFTRCC_Submit = item.AFTRCC_Submit,
            //        AREA_MANAGER = item.AREA_MANAGER,
            //        BUDGET_YEAR = item.BUDGET_YEAR,
            //        CAPITAL_PROGRAM = item.CAPITAL_PROGRAM,
            //        Carrier_Count = item.Carrier_Count,
            //        CASPR_PROJECT_NUMBER = item.CASPR_PROJECT_NUMBER,
            //        CASPR_PROJECT_SEQ = item.CASPR_PROJECT_SEQ,
            //        CFAS_PROJECT_NUMBER = item.CFAS_PROJECT_NUMBER,
            //        CI001_ACTUAL = item.CI001_ACTUAL,
            //        CI001_FORECAST = item.CI001_FORECAST,
            //        CI004_ACTUAL = item.CI004_ACTUAL,
            //        CI004_FORECAST = item.CI004_FORECAST,
            //        CI010_ACTUAL = item.CI010_ACTUAL,
            //        CI010_FORECAST = item.CI010_FORECAST,
            //        CI014_ACTUAL = item.CI014_ACTUAL,
            //        CI014_FORECAST = item.CI014_FORECAST,
            //        CI018_ACTUAL = item.CI018_ACTUAL,
            //        CI018_FORECAST = item.CI018_FORECAST,
            //        CI019_ACTUAL = item.CI019_ACTUAL,
            //        CI019_FORECAST = item.CI019_FORECAST,
            //        CI020_ACTUAL = item.CI020_ACTUAL,
            //        CI020_FORECAST = item.CI020_FORECAST,
            //        CI025_ACTUAL = item.CI025_ACTUAL,
            //        CI025_FORECAST = item.CI025_FORECAST,
            //        CI026_ACTUAL = item.CI026_ACTUAL,
            //        CI026_FORECAST = item.CI026_FORECAST,
            //        CI030_ACTUAL = item.CI030_ACTUAL,
            //        CI030_FORECAST = item.CI030_FORECAST,
            //        CI031_ACTUAL = item.CI031_ACTUAL,
            //        CI031_FORECAST = item.CI031_FORECAST,
            //        CI032_ACTUAL = item.CI032_ACTUAL,
            //        CI032_FORECAST = item.CI032_FORECAST,
            //        CI034_ACTUAL = item.CI034_ACTUAL,
            //        CI034_FORECAST = item.CI034_FORECAST,
            //        CI035_ACTUAL = item.CI035_ACTUAL,
            //        CI035_FORECAST = item.CI035_FORECAST,
            //        CI038_ACTUAL = item.CI038_ACTUAL,
            //        CI038_FORECAST = item.CI038_FORECAST,
            //        CI042_ACTUAL = item.CI042_ACTUAL,
            //        CI042_FORECAST = item.CI042_FORECAST,
            //        CI045_ACTUAL = item.CI045_ACTUAL,
            //        CI045_FORECAST = item.CI045_FORECAST,
            //        CI046_ACTUAL = item.CI046_ACTUAL,
            //        CI046_FORECAST = item.CI046_FORECAST,
            //        CI048_ACTUAL = item.CI048_ACTUAL,
            //        CI048_FORECAST = item.CI048_FORECAST,
            //        CI050_ACTUAL = item.CI050_ACTUAL,
            //        CI050_FORECAST = item.CI050_FORECAST,
            //        CI060_ACTUAL = item.CI060_ACTUAL,
            //        CI060_FORECAST = item.CI060_FORECAST,
            //        CI110_ACTUAL = item.CI110_ACTUAL,
            //        CI110_FORECAST = item.CI110_FORECAST,
            //        CI173_ACTUAL = item.CI173_ACTUAL,
            //        CI173_FORECAST = item.CI173_FORECAST,
            //        CIVIL_VENDOR = item.CIVIL_VENDOR,
            //        CL001_ACTUAL = item.CL001_ACTUAL,
            //        CL001_FORECAST = item.CL001_FORECAST,
            //        CL100_ACTUAL = item.CL100_ACTUAL,
            //        CL100_FORECAST = item.CL100_FORECAST,
            //        COMMITTED_POR_ONAIRDATE = item.COMMITTED_POR_ONAIRDATE,
            //        CONSTRUCTION_TYPE = item.CONSTRUCTION_TYPE,
            //        COUNTY = item.COUNTY,
            //        CURRENT_NEED_BY_DATE = item.CURRENT_NEED_BY_DATE,
            //        custom_program = item.custom_program,
            //        C_E_ON_AIR_DATE = item.C_E_ON_AIR_DATE,
            //        Dist_Zone = item.Dist_Zone,
            //        EDP_Publish_Date = item.EDP_Publish_Date,
            //        EDP_STATUS = item.EDP_STATUS,
            //        EQUIPMENT_VENDOR = item.EQUIPMENT_VENDOR,
            //        EXECUTED_ON = item.EXECUTED_ON,
            //        FA_LOCATION_CODE = item.FA_LOCATION_CODE,
            //        FA_LOCATION_TYPE = item.FA_LOCATION_TYPE,
            //        FIPS_CODE = item.FIPS_CODE,
            //        FREQUENCY = item.FREQUENCY,
            //        Funding_Level = item.Funding_Level,
            //        Funding_Level_Handle = item.Funding_Level_Handle,
            //        High_Trust = item.High_Trust,
            //        IPLAN_JOB_STATUS = item.IPLAN_JOB_STATUS,
            //        ISSUE_DATE_ORIGINAL_ACTUAL = item.ISSUE_DATE_ORIGINAL_ACTUAL,
            //        JOB_SCOPE = item.JOB_SCOPE,
            //        JOB_TYPE_SUBTYPE = item.JOB_TYPE_SUBTYPE,
            //        JOB_VENDOR = item.JOB_VENDOR,
            //        Jurisdiction = item.Jurisdiction,
            //        LATITUDE = item.LATITUDE,
            //        LAUNCH_POLYGON = item.LAUNCH_POLYGON,
            //        LONGITUDE = item.LONGITUDE,
            //        MODCD_Parity_Flag = item.MODCD_Parity_Flag,
            //        MOD_Code = item.MOD_Code,
            //        NATIONAL_PROGRAM = item.NATIONAL_PROGRAM,
            //        NSB_RANKING = item.NSB_RANKING,
            //        ONAIR_ACTUAL = item.ONAIR_ACTUAL,
            //        ONAIR_FORECAST = item.ONAIR_FORECAST,
            //        ONAIR_PLAN = item.ONAIR_PLAN,
            //        ONAIR_TASK = item.ONAIR_TASK,
            //        ORACLE_PTN = item.ORACLE_PTN,
            //        ORIGINAL_NEED_BY_DATE = item.ORIGINAL_NEED_BY_DATE,
            //        PACE_NAME = item.PACE_NAME,
            //        PACE_NUMBER = item.PACE_NUMBER,
            //        PHASE = item.PHASE,
            //        PLAN_FC_On_Air = item.PLAN_FC_On_Air,
            //        PM2_Person = item.PM2_Person,
            //        PM3_Person = item.PM3_Person,
            //        POE_Name = item.POE_Name,
            //        POE_Status = item.POE_Status,
            //        POLYGON_JID = item.POLYGON_JID,
            //        POR_Name = item.POR_Name,
            //        POR_ONAIR_PLAN = item.POR_ONAIR_PLAN,
            //        POR_Status = item.POR_Status,
            //        Primary_Job_Number = item.Primary_Job_Number,
            //        PRODUCT_GROUP = item.PRODUCT_GROUP,
            //        PRODUCT_SUBGROUP = item.PRODUCT_SUBGROUP,
            //        PROJECT_MANAGER = item.PROJECT_MANAGER,
            //        RBS_ID = item.RBS_ID,
            //        RE001_ACTUAL = item.RE001_ACTUAL,
            //        RE001_FORECAST = item.RE001_FORECAST,
            //        RE005_ACTUAL = item.RE005_ACTUAL,
            //        RE005_FORECAST = item.RE005_FORECAST,
            //        RE015_ACTUAL = item.RE015_ACTUAL,
            //        RE015_FORECAST = item.RE015_FORECAST,
            //        RE020_ACTUAL = item.RE020_ACTUAL,
            //        RE020_FORECAST = item.RE020_FORECAST,
            //        RE030_ACTUAL = item.RE030_ACTUAL,
            //        RE030_FORECAST = item.RE030_FORECAST,
            //        RE031_ACTUAL = item.RE031_ACTUAL,
            //        RE031_FORECAST = item.RE031_FORECAST,
            //        RE032_ACTUAL = item.RE032_ACTUAL,
            //        RE032_FORECAST = item.RE032_FORECAST,
            //        RE046_ACTUAL = item.RE046_ACTUAL,
            //        RE046_FORECAST = item.RE046_FORECAST,
            //        RE047_ACTUAL = item.RE047_ACTUAL,
            //        RE047_FORECAST = item.RE047_FORECAST,
            //        RE055_ACTUAL = item.RE055_ACTUAL,
            //        RE055_FORECAST = item.RE055_FORECAST,
            //        RE056_ACTUAL = item.RE056_ACTUAL,
            //        RE056_FORECAST = item.RE056_FORECAST,
            //        RE060_ACTUAL = item.RE060_ACTUAL,
            //        RE060_FORECAST = item.RE060_FORECAST,
            //        RE066_ACTUAL = item.RE066_ACTUAL,
            //        REGIONFRANCHISE_INDICATOR = item.REGIONFRANCHISE_INDICATOR,
            //        RFDS_ID = item.RFDS_ID,
            //        RFDS_State_Status = item.RFDS_State_Status,
            //        RFDS_Workflow_Owner = item.RFDS_Workflow_Owner,
            //        SEARCH_RING_ID = item.SEARCH_RING_ID,
            //        SEARCH_RING_NAME = item.SEARCH_RING_NAME,
            //        SITE_ACQUISITION_VENDOR = item.SITE_ACQUISITION_VENDOR,
            //        SITE_ID = item.SITE_ID,
            //        Site_Submission_Status = item.Site_Submission_Status,
            //        SOURCE_JOB_NUMBER = item.SOURCE_JOB_NUMBER,
            //        SPECTRUM = item.SPECTRUM,
            //        Spectrum_Bucket = item.Spectrum_Bucket,
            //        SS002_ACTUAL = item.SS002_ACTUAL,
            //        SS002_FORECAST = item.SS002_FORECAST,
            //        SS009_ACTUAL = item.SS009_ACTUAL,
            //        SS009_FORECAST = item.SS009_FORECAST,
            //        SS010_ACTUAL = item.SS010_ACTUAL,
            //        SS010_FORECAST = item.SS010_FORECAST,
            //        SS011_ACTUAL = item.SS011_ACTUAL,
            //        SS011_FORECAST = item.SS011_FORECAST,
            //        SS019_ACTUAL = item.SS019_ACTUAL,
            //        SS019_FORECAST = item.SS019_FORECAST,
            //        SS020_ACTUAL = item.SS020_ACTUAL,
            //        SS020_FORECAST = item.SS020_FORECAST,
            //        SS055_ACTUAL = item.SS055_ACTUAL,
            //        SS055_FORECAST = item.SS055_FORECAST,
            //        SS059_ACTUAL = item.SS059_ACTUAL,
            //        SS059_FORECAST = item.SS059_FORECAST,
            //        STATUS = item.STATUS,
            //        STRATEGIC_DRIVER = item.STRATEGIC_DRIVER,
            //        TECHNOLOGY = item.TECHNOLOGY,
            //        Temp_2 = item.Temp_2,
            //        TRANSPORT_TYPE = item.TRANSPORT_TYPE,
            //        _1_2_1900 = item._1_2_1900                                            
            //    });
            //}
            //return lstWaterfall_NSB_Data;
        }
    }
}

